package com.example.lapcs;

import java.util.Arrays;
import java.util.Collection;

public class AppConsts {

    //-------------------------------Application Constants-------------------

    public static final String TAG = "MyTag";
    public static final String LAPCS_CHANNEL_ID = "LAPCS_CHANNEL_ID";
    public static final String LAPCS_LOCATION_CHANNEL_ID = "LAPCS_LOCATION_CHANNEL_ID";
    public static final String LAPCS_SOS_CHANNEL_ID = "LAPCS_SOS_CHANNEL_ID";

    public static final int INITIAL_DELAY_IN_SECONDS = 5*1000;

    private static final int REQUIRED_INTERVAL_IN_SECONDS = 10;
    public static final long NOTIFY_INTERVAL = REQUIRED_INTERVAL_IN_SECONDS* 1000;

    public static final int Notification_ID = 1002;
    public static final int Location_Notification_ID = 1003;

    public static final String SHARED_PREF_NAME = "LAPCS_SHARED_PREF";



    //lapcs1234
    public static final String Server_API_key       = "key=AAAAfRuu2i8:APA91bHcxlqlxwwpy5QSD_LXV2KlkUBpmGn50NK7cYiIZtJoC-IvctP1TDm2fR53Bv40j0YHFop_Fi1TF4WcR9vOXrJlez6GlKjWEEyF13fn9C4N9Ewwe7Rc4GMLjpf2HNkmj0FtINOx";
    public static final String ContentType          = "application/json";

    public static final String Users_Node_Ref                       = "Users";
    public static final String Mobiles_Node_Ref                     = "Mobiles";
    public static final String Child_Meta_Data_Node_Ref             = "ChildMetaData";
    public static final String Parent_Meta_Data_Node_Ref            = "ParentMetaData";

    public static final String PROX_ALERT_INTENT = "com.example.lapcs.ProximityAlert";


    public static final Collection<String> HarassmentWordsList = Arrays.asList("touching",
                                                                                "groping",
                                                                                "whistles",
                                                                                "sexual",
                                                                                "stalking",
                                                                                "commenting",
                                                                                "rape",
                                                                                "indecent",
                                                                                "snatching",
                                                                                "ogling",
                                                                                "facial",
                                                                                "staring",
                                                                                "pictures",
                                                                                "poor",
                                                                                "harassment",
                                                                                "torment",
                                                                                "persecution",
                                                                                "bother",
                                                                                "bad behavior",
                                                                                "bullying",
                                                                                "intimidation",
                                                                                "trouble",
                                                                                "molestation",
                                                                                "harass",
                                                                                "harassed",
                                                                                "annoyance",
                                                                                "irritation",
                                                                                "provocation",
                                                                                "disturbance",
                                                                                "harassing",
                                                                                "vexation",
                                                                                "bully",
                                                                                "aggravation",
                                                                                "hassle",
                                                                                "agony",
                                                                                "bedevilment",
                                                                                "stalk",
                                                                                "mobbing",
                                                                                "pressure",
                                                                                "besieging",
                                                                                "stalking",
                                                                                "bothering",
                                                                                "molesting",
                                                                                "manhunt",
                                                                                "bullied",
                                                                                "force",
                                                                                "pestered",
                                                                                "teasing",
                                                                                "grief",
                                                                                "upset",
                                                                                "badgering",
                                                                                "inconvenience",
                                                                                "anguish",
                                                                                "nuisance",
                                                                                "worry",
                                                                                "pester",
                                                                                "botheration",
                                                                                "exasperation",
                                                                                "siege",
                                                                                "plague",
                                                                                "pest",
                                                                                "oppression",
                                                                                "molested",
                                                                                "assault",
                                                                                "persecuted",
                                                                                "hazing",
                                                                                "coercion",
                                                                                "perturbation",
                                                                                "headache",
                                                                                "chicane",
                                                                                "difficulty",
                                                                                "worrying",
                                                                                "intimidate",
                                                                                "anti-harassment",
                                                                                "excruciation",
                                                                                "suffering",
                                                                                "harrying",
                                                                                "slander",
                                                                                "defamation",
                                                                                "persecuting",
                                                                                "abuse",
                                                                                "prosecution",
                                                                                "harassments",
                                                                                "problem",
                                                                                "torture",
                                                                                "distress",
                                                                                "anxiety",
                                                                                "illtreatment",
                                                                                "curse",
                                                                                "intimidatory",
                                                                                "victimization",
                                                                                "intimidating",
                                                                                "pestering",
                                                                                "besiegement",
                                                                                "heartache",
                                                                                "nagging",
                                                                                "pursuit",
                                                                                "cyberbullying",
                                                                                "hot pursuit",
                                                                                "hounding",
                                                                                "libel",
                                                                                "calumny",
                                                                                "badger",
                                                                                "vexations",
                                                                                "harrass",
                                                                                "importuning",
                                                                                "chicanes",
                                                                                "bothered",
                                                                                "badgered",
                                                                                "seige",
                                                                                "chasing",
                                                                                "bugging",
                                                                                "persecutions",
                                                                                "trial",
                                                                                "he stalked",
                                                                                "harassing her",
                                                                                "pain",
                                                                                "hectoring",
                                                                                "indignities",
                                                                                "misery",
                                                                                "plaguing",
                                                                                "smear campaign",
                                                                                "taunting",
                                                                                "harasses",
                                                                                "stalker-y",
                                                                                "hint",
                                                                                "he accosted",
                                                                                "persecute",
                                                                                "irking",
                                                                                "besieged",
                                                                                "calumnies",
                                                                                "intimidated",
                                                                                "scare",
                                                                                "hound",
                                                                                "sieges",
                                                                                "despair",
                                                                                "despondency",
                                                                                "discomfort",
                                                                                "stalky",
                                                                                "persuit",
                                                                                "scorn",
                                                                                "insults",
                                                                                "stalkery",
                                                                                "you harassing",
                                                                                "tribulation",
                                                                                "obloquy",
                                                                                "stigmatization",
                                                                                "molest",
                                                                                "smear",
                                                                                "blockade",
                                                                                "slurs",
                                                                                "disturb",
                                                                                "defamatory",
                                                                                "besiege",
                                                                                "embargo",
                                                                                "annoyances",
                                                                                "hazed",
                                                                                "from abusing",
                                                                                "accosted",
                                                                                "compulsion",
                                                                                "victimise",
                                                                                "hounded",
                                                                                "encroaching",
                                                                                "baiting",
                                                                                "fret",
                                                                                "frustration",
                                                                                "prosecuting them",
                                                                                "be harassed",
                                                                                "agitation",
                                                                                "prodding",
                                                                                "terrorizing",
                                                                                "discouragement",
                                                                                "annoy",
                                                                                "affront",
                                                                                "goading",
                                                                                "incitement",
                                                                                "strife",
                                                                                "harried",
                                                                                "constraint",
                                                                                "groped",
                                                                                "duress",
                                                                                "vexing",
                                                                                "provoking",
                                                                                "arm-twisting",
                                                                                "encirclement",
                                                                                "slanders",
                                                                                "teased",
                                                                                "being hounded",
                                                                                "nettling",
                                                                                "mistreatment",
                                                                                "distraction",
                                                                                "stalker",
                                                                                "threat",
                                                                                "pains",
                                                                                "discomposure",
                                                                                "mental anguish",
                                                                                "gauntlet",
                                                                                "tormenting",
                                                                                "mental distress",
                                                                                "scaring",
                                                                                "cyberbully",
                                                                                "problems",
                                                                                "troubles",
                                                                                "rousing",
                                                                                "stress",
                                                                                "wearisomeness",
                                                                                "unpleasantness",
                                                                                "humiliation",
                                                                                "sea of grief",
                                                                                "car chases",
                                                                                "stalked",
                                                                                "complex question",
                                                                                "vivien",
                                                                                "filthy hands",
                                                                                "steam coming out of ears",
                                                                                "invitation",
                                                                                "stirring",
                                                                                "surrounded",
                                                                                "bad news",
                                                                                "affliction",
                                                                                "inconveniences",
                                                                                "anti-bullying",
                                                                                "care",
                                                                                "dejection",
                                                                                "depression",
                                                                                "bickering",
                                                                                "stimulation",
                                                                                "grievance",
                                                                                "been stalking",
                                                                                "stalking her",
                                                                                "dissatisfaction",
                                                                                "baffle",
                                                                                "disturb you",
                                                                                "heavy hand",
                                                                                "interference",
                                                                                "intrusion",
                                                                                "drag",
                                                                                "upset you",
                                                                                "ill treatment",
                                                                                "prompting",
                                                                                "wall",
                                                                                "ultimatum",
                                                                                "harrassment",
                                                                                "aggro",
                                                                                "admonition",
                                                                                "malicious prosecution",
                                                                                "being abused",
                                                                                "violation",
                                                                                "hot water",
                                                                                "intrude",
                                                                                "disturbed",
                                                                                "bad treatment",
                                                                                "abused",
                                                                                "chase",
                                                                                "libellous",
                                                                                "encouragement",
                                                                                "hassled",
                                                                                "summons",
                                                                                "slandering",
                                                                                "troubled",
                                                                                "follow",
                                                                                "downer",
                                                                                "nuisances",
                                                                                "unfriendliness",
                                                                                "pursue",
                                                                                "goad",
                                                                                "prosecute",
                                                                                "injury",
                                                                                "urging",
                                                                                "been picking",
                                                                                "disruption",
                                                                                "martial law",
                                                                                "bothersomeness",
                                                                                "repression",
                                                                                "agro",
                                                                                "prosecuting",
                                                                                "devilment",
                                                                                "warning",
                                                                                "workplace stalking",
                                                                                "concern",
                                                                                "anger",
                                                                                "being stalked",
                                                                                "foreboding",
                                                                                "bluster",
                                                                                "prosecuted",
                                                                                "monition",
                                                                                "tease",
                                                                                "criminal harassment",
                                                                                "haunt",
                                                                                "been bugging me",
                                                                                "inspiration",
                                                                                "inflammation",
                                                                                "troublesomeness",
                                                                                "been pestering me",
                                                                                "arousal",
                                                                                "perplex",
                                                                                "petulance",
                                                                                "mess",
                                                                                "charge",
                                                                                "ire",
                                                                                "workplace harassment",
                                                                                "virulence",
                                                                                "hangup",
                                                                                "imbroglio",
                                                                                "pique",
                                                                                "sabre-rattling",
                                                                                "brickbat",
                                                                                "raids",
                                                                                "resentment",
                                                                                "casus belli",
                                                                                "maze",
                                                                                "mental burden",
                                                                                "indignation",
                                                                                "challenge",
                                                                                "millstone",
                                                                                "dare",
                                                                                "pinch",
                                                                                "ass in a sling",
                                                                                "exacerbation",
                                                                                "puzzle",
                                                                                "grabber",
                                                                                "ramification",
                                                                                "enragement",
                                                                                "responsibility",
                                                                                "mental disturbance",
                                                                                "indignity",
                                                                                "inducement",
                                                                                "vicissitude",
                                                                                "weight",
                                                                                "complex situation",
                                                                                "persuasion",
                                                                                "stimulus",
                                                                                "taunt",
                                                                                "worriment",
                                                                                "peskiness",
                                                                                "threats",
                                                                                "smoke coming out of ears",
                                                                                "witch-hunt",
                                                                                "red-baiting",
                                                                                "irksomeness",
                                                                                "worriedness",
                                                                                "bullying tactics",
                                                                                "annoyingness",
                                                                                "crashing bore",
                                                                                "in the chase",
                                                                                "tiresomeness",
                                                                                "witch-hunting",
                                                                                "egging on",
                                                                                "provokingness",
                                                                                "deflector",
                                                                                "vexatiousness",
                                                                                "maltreatment",
                                                                                "worrisomeness",
                                                                                "plaguesomeness",
                                                                                "fretting",
                                                                                "pestiferousness",
                                                                                "bane",
                                                                                "worries and cares",
                                                                                "from encroaching",
                                                                                "bore",
                                                                                "ails",
                                                                                "tortures",
                                                                                "re-victimization",
                                                                                "has been terrorizing",
                                                                                "hurting",
                                                                                "incenses",
                                                                                "discouraging",
                                                                                "sexual harassment",
                                                                                "victimize",
                                                                                "continue",
                                                                                "invade",
                                                                                "tiring",
                                                                                "victimizing",
                                                                                "tedious",
                                                                                "damage",
                                                                                "ribbing",
                                                                                "ragging",
                                                                                "abominable",
                                                                                "prosecute them",
                                                                                "tempt",
                                                                                "casting aspersions",
                                                                                "humiliated",
                                                                                "enraging",
                                                                                "trapped",
                                                                                "intimidate them",
                                                                                "terrorize",
                                                                                "keeping",
                                                                                "impinging",
                                                                                "dispute",
                                                                                "aggravate",
                                                                                "anti-terrorism",
                                                                                "bring them to justice",
                                                                                "harm",
                                                                                "forewarning",
                                                                                "obstacle",
                                                                                "campaign of defamation",
                                                                                "badassery",
                                                                                "sexualized",
                                                                                "tried",
                                                                                "terrorism",
                                                                                "been harassing her",
                                                                                "anguishing",
                                                                                "bating",
                                                                                "oppressed",
                                                                                "been harassing",
                                                                                "he followed",
                                                                                "prosecutions",
                                                                                "annoying",
                                                                                "sexually harassed",
                                                                                "indecent",
                                                                                "pursuing",
                                                                                "tyrant",
                                                                                "exasperates",
                                                                                "stalked her",
                                                                                "retaliation",
                                                                                "fight",
                                                                                "terrorist",
                                                                                "henpeck",
                                                                                "website",
                                                                                "provocateur",
                                                                                "flogger",
                                                                                "bother you",
                                                                                "bringing them to justice",
                                                                                "infringing",
                                                                                "obnoxious",
                                                                                "puller",
                                                                                "malware",
                                                                                "defamation campaign",
                                                                                "anti-terrorist",
                                                                                "outrage",
                                                                                "angst",
                                                                                "bemoaning",
                                                                                "physical abuse",
                                                                                "bereavement",
                                                                                "traffickers",
                                                                                "bewailing",
                                                                                "harass her",
                                                                                "besetment",
                                                                                "tame",
                                                                                "terrorised",
                                                                                "somewhere",
                                                                                "manhunts",
                                                                                "terrorizes",
                                                                                "deploring",
                                                                                "proceedings against them",
                                                                                "kibitzer",
                                                                                "desolation",
                                                                                "terrified",
                                                                                "intimidating them",
                                                                                "deterrent",
                                                                                "hector",
                                                                                "contempt",
                                                                                "terrify",
                                                                                "agonize",
                                                                                "banishment",
                                                                                "disquiet",
                                                                                "tail",
                                                                                "trespassing",
                                                                                "loathsome",
                                                                                "whisper campaign",
                                                                                "bashing",
                                                                                "dole",
                                                                                "discrimination",
                                                                                "dolor",
                                                                                "track",
                                                                                "pothered",
                                                                                "exile",
                                                                                "gloom",
                                                                                "expulsion",
                                                                                "ill treated",
                                                                                "he chased",
                                                                                "galling",
                                                                                "hell",
                                                                                "place",
                                                                                "ill-treatment",
                                                                                "nag",
                                                                                "heartbreak",
                                                                                "blockaded",
                                                                                "imprisonment",
                                                                                "infelicity",
                                                                                "infliction",
                                                                                "pain in the neck",
                                                                                "aggravator",
                                                                                "lamentation",
                                                                                "killing",
                                                                                "chivy",
                                                                                "rack",
                                                                                "lamenting",
                                                                                "massacre",
                                                                                "scourge",
                                                                                "malaise",
                                                                                "follow her",
                                                                                "murder",
                                                                                "melancholy",
                                                                                "mental suffering",
                                                                                "watched her",
                                                                                "infringement",
                                                                                "mortification",
                                                                                "irritants",
                                                                                "unworthiness",
                                                                                "chafe",
                                                                                "importunity",
                                                                                "mournfulness",
                                                                                "mourning",
                                                                                "humiliating",
                                                                                "purgatory",
                                                                                "dirty tricks campaign",
                                                                                "expose it",
                                                                                "remorse",
                                                                                "irk",
                                                                                "humiliate",
                                                                                "repining",
                                                                                "rue",
                                                                                "site",
                                                                                "humiliations",
                                                                                "sadness",
                                                                                "aspersions",
                                                                                "sorrow",
                                                                                "cornered",
                                                                                "used",
                                                                                "unhappiness",
                                                                                "groping",
                                                                                "discomfiture",
                                                                                "importunateness",
                                                                                "misused",
                                                                                "woe",
                                                                                "unpleasant feeling",
                                                                                "wretchedness",
                                                                                "incensing",
                                                                                "weariness",
                                                                                "chicano",
                                                                                "abusing",
                                                                                "uncomfortable feeling",
                                                                                "castle",
                                                                                "insider",
                                                                                "unpleasant sensation",
                                                                                "terrorized",
                                                                                "sexually",
                                                                                "blockading",
                                                                                "displeasure",
                                                                                "campaign of vilification",
                                                                                "sexual",
                                                                                "irritates",
                                                                                "seines",
                                                                                "man-hunts",
                                                                                "puberty",
                                                                                "purse-seine",
                                                                                "besieger",
                                                                                "be bothered",
                                                                                "fasten",
                                                                                "fibrous",
                                                                                "unrest",
                                                                                "mistreated",
                                                                                "beleaguered",
                                                                                "encroachment",
                                                                                "bothered you",
                                                                                "persecutory",
                                                                                "bully them",
                                                                                "textile",
                                                                                "irritant",
                                                                                "fence",
                                                                                "obtrusion",
                                                                                "pesters",
                                                                                "fibrosis",
                                                                                "hairpin",
                                                                                "breached",
                                                                                "surrounding",
                                                                                "afflict",
                                                                                "non fibrous",
                                                                                "broken",
                                                                                "drive-by smear",
                                                                                "scare them",
                                                                                "fibrotic",
                                                                                "was molesting",
                                                                                "raped",
                                                                                "bug",
                                                                                "fibre",
                                                                                "violated",
                                                                                "fabrications",
                                                                                "disagreeable",
                                                                                "fiber",
                                                                                "invasion",
                                                                                "be bullied",
                                                                                "upsetting",
                                                                                "plagued",
                                                                                "bad word",
                                                                                "disturbing",
                                                                                "in the persecution",
                                                                                "slander campaign",
                                                                                "disrepute",
                                                                                "beating",
                                                                                "terrorising",
                                                                                "stalk her",
                                                                                "under siege",
                                                                                "laid siege",
                                                                                "slanderous",
                                                                                "battery",
                                                                                "car chase",
                                                                                "lay siege",
                                                                                "assaulting",
                                                                                "without infringing",
                                                                                "disinformation campaign",
                                                                                "chicanery",
                                                                                "irksome",
                                                                                "chivying",
                                                                                "unencumbered",
                                                                                "two cheques",
                                                                                "horrification",
                                                                                "two checks",
                                                                                "prosecutorial overcharging",
                                                                                "tormented",
                                                                                "troublesome",
                                                                                "dirty campaign",
                                                                                "malign",
                                                                                "objectionable",
                                                                                "you are bothering",
                                                                                "abusiveness",
                                                                                "libels",
                                                                                "cast aspersions",
                                                                                "autocracy",
                                                                                "brutality",
                                                                                "disrupt",
                                                                                "calamity",
                                                                                "conquering",
                                                                                "pothering",
                                                                                "control",
                                                                                "been pestering",
                                                                                "despotism",
                                                                                "without encroaching",
                                                                                "dictatorship",
                                                                                "vilification",
                                                                                "domination",
                                                                                "snide remarks",
                                                                                "fascism",
                                                                                "haunted",
                                                                                "complex problem",
                                                                                "forcibleness",
                                                                                "turmoil",
                                                                                "hardness",
                                                                                "hardship",
                                                                                "psychological harassment",
                                                                                "disorder",
                                                                                "harshness",
                                                                                "slandered",
                                                                                "slur",
                                                                                "cough",
                                                                                "damaged",
                                                                                "injustice",
                                                                                "malicious accusation",
                                                                                "oppressive",
                                                                                "iron hand",
                                                                                "baited",
                                                                                "tricky",
                                                                                "besmirch",
                                                                                "nags me",
                                                                                "persecutors",
                                                                                "overthrowing",
                                                                                "tortured",
                                                                                "unfriendly",
                                                                                "tough",
                                                                                "disorders",
                                                                                "teases",
                                                                                "paranoia",
                                                                                "severity",
                                                                                "libelous",
                                                                                "bugging me",
                                                                                "losses",
                                                                                "subduing",
                                                                                "intrusive",
                                                                                "persecution complex",
                                                                                "subjection",
                                                                                "hard",
                                                                                "injuries",
                                                                                "closure",
                                                                                "tra-la-la",
                                                                                "subjugation",
                                                                                "raiding",
                                                                                "man hunt",
                                                                                "being paranoid",
                                                                                "tyranny",
                                                                                "mistreatments",
                                                                                "difficult",
                                                                                "do you bother",
                                                                                "blockades",
                                                                                "tyrrany",
                                                                                "cowing",
                                                                                "bothering me",
                                                                                "embargoes",
                                                                                "desperation",
                                                                                "hunting people",
                                                                                "pasteur",
                                                                                "hedges",
                                                                                "disconsolateness",
                                                                                "fear",
                                                                                "standoff",
                                                                                "gossip",
                                                                                "felons",
                                                                                "fester",
                                                                                "fences",
                                                                                "hopelessness",
                                                                                "nervousness",
                                                                                "curfew",
                                                                                "pang",
                                                                                "haze",
                                                                                "annoys",
                                                                                "accusation",
                                                                                "complication",
                                                                                "beyond",
                                                                                "crisis",
                                                                                "emergency",
                                                                                "harry",
                                                                                "nuisance suit",
                                                                                "chumming",
                                                                                "exigency",
                                                                                "being picked",
                                                                                "ado",
                                                                                "bafflement",
                                                                                "ailed",
                                                                                "this siege",
                                                                                "entice",
                                                                                "perplexity",
                                                                                "terror",
                                                                                "pickle",
                                                                                "anti-stalking",
                                                                                "quandary",
                                                                                "embarrassment",
                                                                                "scrape",
                                                                                "combating bullying",
                                                                                "trafficked",
                                                                                "strain",
                                                                                "aggrieve",
                                                                                "strait",
                                                                                "traitors",
                                                                                "tackling bullying",
                                                                                "irritating",
                                                                                "jam",
                                                                                "exceed",
                                                                                "disgusting",
                                                                                "cause",
                                                                                "oppress",
                                                                                "haze over",
                                                                                "pillaging",
                                                                                "draining",
                                                                                "interfere",
                                                                                "defy",
                                                                                "humdrum",
                                                                                "beset",
                                                                                "grounds",
                                                                                "predicament",
                                                                                "besetting",
                                                                                "aggression",
                                                                                "setback",
                                                                                "mist",
                                                                                "attacks",
                                                                                "accumulate",
                                                                                "intimidations",
                                                                                "you bully",
                                                                                "agonies",
                                                                                "malicious process",
                                                                                "hostile",
                                                                                "to-do",
                                                                                "been bothering",
                                                                                "extremely",
                                                                                "usurping",
                                                                                "you bug",
                                                                                "impatience",
                                                                                "fog",
                                                                                "instigation",
                                                                                "invader",
                                                                                "determent",
                                                                                "insult",
                                                                                "harassment in the workplace",
                                                                                "baffle plates",
                                                                                "you harass",
                                                                                "justification",
                                                                                "hostility",
                                                                                "invasive",
                                                                                "motivation",
                                                                                "fatalities",
                                                                                "mental abuse",
                                                                                "hatred",
                                                                                "baffles",
                                                                                "been terrorizing",
                                                                                "needling",
                                                                                "involve",
                                                                                "niggling",
                                                                                "animosity",
                                                                                "baffling",
                                                                                "offense",
                                                                                "torturer",
                                                                                "criminal violations",
                                                                                "reason",
                                                                                "psychological violence",
                                                                                "hostilities",
                                                                                "baffled",
                                                                                "harassed her",
                                                                                "encroach",
                                                                                "sitting",
                                                                                "enmity",
                                                                                "squabbles",
                                                                                "subjected",
                                                                                "hassling",
                                                                                "noise pollution",
                                                                                "you disturb",
                                                                                "bother her",
                                                                                "irritatingly",
                                                                                "infringe",
                                                                                "malevolent",
                                                                                "mischief",
                                                                                "evil",
                                                                                "victims",
                                                                                "browbeating",
                                                                                "being molested",
                                                                                "prune",
                                                                                "encroaches",
                                                                                "terrifying",
                                                                                "victim",
                                                                                "bedevil",
                                                                                "brickbats",
                                                                                "discouraged",
                                                                                "offend",
                                                                                "acts of intimidation",
                                                                                "tiresome",
                                                                                "casualties",
                                                                                "high dudgeon",
                                                                                "spent",
                                                                                "anathema",
                                                                                "sense of injury",
                                                                                "odious",
                                                                                "blasphemy",
                                                                                "umbrage",
                                                                                "blight",
                                                                                "sue them",
                                                                                "invading",
                                                                                "cuss",
                                                                                "paining",
                                                                                "terrorise",
                                                                                "nasty",
                                                                                "incentive",
                                                                                "mental violence");



    public static final String SEND_MESSAGE_ACTION = "SEND_MESSAGE_ACTION";
    public static final String SEND_ALERT_ACTION = "SEND_ALERT_ACTION";
    public static final String DEFAULT_EMERGENCY_NUMBER = "+923365253021";
    public static final int SEND_MESSAGE_FROM_LOCK_SCREEN_NOTIFICATION_ID = 1004;

    public static final String LOCKSCREEN_SOS_MSG_INTENT = "com.example.lapcs.lockscreen_sos_msg";
    public static final String LOCKSCREEN_SOS_ALERT_INTENT = "com.example.lapcs.lockscreen_sos_alert";


}
